apiVersion: apps/v1
kind: Deployment
metadata:
  name: avs-portaldemidia
  labels:
    app: avs-portaldemidia
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: avs-portaldemidia
      tier: frontend
  template:
    metadata:
      labels:
        app: avs-portaldemidia
        tier: frontend
    spec:
      containers:
        - name: avs-portaldemidia
          image: ${IMAGE}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - secretRef:
                name: avs-portaldemidias-frontend-secrets 
          livenessProbe:
            httpGet:
              path: /avs-portaldemidia/healthz
              port: http
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /avs-portaldemidia/healthz
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"

---

apiVersion: v1
kind: Service
metadata:
  name: avs-portaldemidia
  labels:
    app: avs-portaldemidia
    tier: frontend
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: avs-portaldemidia
    tier: frontend

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: avs-portaldemidia
  namespace: default
  labels:
    app: avs-portaldemidia
    tier: frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: avs-portaldemidia
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75